### ISSUE TITLE
Safari Nets are able to be used as leads on mobs

### ISSUE THREAD

**Issue by apmarsenault** [firestarter/bulletin#31]
Right clicking a mob with a safari net with a mob inside it attaches a lead to the mob, effectively erasing the safari net's contents. (Tested on bees with bee safari net)

**Comment by nkomarn** [comment]
This has been resolved as of 7caabf33d9b1be09efbcab97d24bb68913be6b12.

**Comment by nkomarn** [comment]
This has been resolved as of https://github.com/firestarter/plugins/commit/7caabf33d9b1be09efbcab97d24bb68913be6b12.
