### ISSUE TITLE
Using /back after a spawn void RTP causes you to fall into the void

### ISSUE THREAD

**Issue by apmarsenault** [firestarter/bulletin#35]
Steps to reproduce:

1. Go to spawn, and jump off the spawn island into the void.
2. You will be RTP'ed somewhere.
3. Do /back
4. Die in the void!

**Comment by nkomarn** [comment]
This has been resolved as of https://github.com/firestarter/plugins/commit/ce5938e68626844ee7808abf8058e317d7bd15ff.
