### ISSUE TITLE
Falling out of spawn does not cause /rtp

### ISSUE THREAD

**Issue by apmarsenault** [firestarter/bulletin#4]
Falling out of spawn (potentially only in certain areas? Untested) will cause the player to fall into the void and lose their inventory/gear instead of causing them to `/rtp`

**Comment by nkomarn** [comment]
I believe this only happens to players with higher ping who do not teleport in time before dying to the void. A barrier layer should be added to the bottom of the spawn world and the height at which the RTP action is triggered should be increased.
