### ISSUE TITLE
Agrarian Gig - Decomposer perk yields infinite bonemeal

### ISSUE THREAD

**Issue by YahooFlop** [firestarter/bulletin#48]
- The decomposer perk for the agrarian gig allows for bonemeal to be obtained when picking up any crop, regardless of whether it was freshly farmed
- Initially tested by emptying a large quantity of brown mushrooms out of a chest and picking them back up; a proportional amount of bonemeal was produced as a biproduct

**Comment by nkomarn** [comment]
Thank you for the report. I've reworked this perk to drop bone meal when crop blocks are harvested rather than when crops are picked up by a player.
